name: Deploy to github pages
run-name: run-name for this action
on:
  push:
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  example-job:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Setup nodejs environment on the runner
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Configuring git
        run: |
          git config --global user.name '${{ github.repository_owner }}'
          git config --global user.email '${{ github.repository_owner }}@users.noreply.github.com'
          git remote set-url origin https://github.com/${{ github.repository }}.git
      - name: finally deploy 
        run: |
          npm run predeploy
          npm run deploy
