name: Deploy to Github Pages
run-name: deploy-to-github-pages
on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    main-job:
        name: Main
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: setup nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: installing dependencies
              run: npm ci
            - name: configuring git
              run: |
                  git config --global user.name '${{ github.repository_owner }}'
                  git config --global user.email '${{ github.repository_owner }}@users.noreply.github.com'
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            - name: run deployment script
              run: |
                  npm run predeploy
                  npm run deploy
